# Generated by Django 4.0.2 on 2022-02-12 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list2', '0004_alter_info_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='phone',
        ),
    ]
