# Generated by Django 2.2.12 on 2022-02-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list2', '0005_remove_info_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='list2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='info',
        ),
    ]
