# Generated by Django 4.0.2 on 2022-02-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list2', '0006_auto_20220212_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list2',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
